### PR TITLE
Upgrade node to 12

### PR DESCRIPTION
**Pull request by stephengeller**
Deployed to PROD, no errors reported and invocations look healthy. This is part of [this card](https://trello.com/c/fF1RDUtJ/167-update-node).

### CODE REVIEW

**Comment by sihil** [comment]
Shall we try and get this merged @stephengeller  ?

**Comment by sihil** [comment]
Looks like it conflcts with https://github.com/guardian/cloudwatch-logs-management/pull/18

**Comment by sihil** [comment]
The node engine is also specified in the `.nvmrc` and `package.json`. The latter might be ignored but the former is using during the build.

**Comment by jacobwinch** [comment]
This has conflicts so I'll close it in favour of https://github.com/guardian/cloudwatch-logs-management/pull/46.

**Pull request closed without merging**
